// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "플레이어 로그인을 처리하고 JWT 토큰을 반환합니다",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "로그인",
                "parameters": [
                    {
                        "description": "로그인 정보",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/game_eating_pizza_internal_api_dto.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "로그인 성공",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "잘못된 요청",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "인증 실패",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/auth/refresh": {
            "post": {
                "description": "JWT 토큰을 갱신합니다",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "토큰 갱신",
                "parameters": [
                    {
                        "description": "토큰 갱신 (바디 없음)",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/game_eating_pizza_internal_api_dto.RefreshTokenRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "토큰 갱신 성공",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "인증 실패",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "새로운 플레이어를 등록합니다",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "회원가입",
                "parameters": [
                    {
                        "description": "회원가입 정보",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/game_eating_pizza_internal_api_dto.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "회원가입 성공",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "잘못된 요청",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "서버 오류",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/dungeons": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "새로운 던전을 생성합니다",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dungeons"
                ],
                "summary": "던전 생성",
                "parameters": [
                    {
                        "description": "던전 생성 정보",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/game_eating_pizza_internal_api_dto.CreateDungeonRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "생성된 던전 정보",
                        "schema": {
                            "$ref": "#/definitions/game_eating_pizza_internal_api_dto.DungeonResponse"
                        }
                    },
                    "400": {
                        "description": "잘못된 요청",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "인증 실패",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "서버 오류",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/dungeons/active": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "활성화된 던전 목록만 조회합니다",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dungeons"
                ],
                "summary": "활성 던전 목록 조회",
                "responses": {
                    "200": {
                        "description": "던전 목록",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/game_eating_pizza_internal_api_dto.DungeonResponse"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "인증 실패",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "서버 오류",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/dungeons/all": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "전체 던전 목록을 조회합니다 (활성/비활성 포함)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dungeons"
                ],
                "summary": "전체 던전 목록 조회",
                "responses": {
                    "200": {
                        "description": "던전 목록",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "인증 실패",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "서버 오류",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/dungeons/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "특정 던전의 상세 정보를 조회합니다",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dungeons"
                ],
                "summary": "던전 상세 조회",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "던전 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "던전 정보",
                        "schema": {
                            "$ref": "#/definitions/game_eating_pizza_internal_api_dto.DungeonResponse"
                        }
                    },
                    "400": {
                        "description": "잘못된 요청",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "인증 실패",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "던전을 찾을 수 없음",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "던전 정보를 수정합니다",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dungeons"
                ],
                "summary": "던전 수정",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "던전 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "수정할 던전 정보",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/game_eating_pizza_internal_api_dto.UpdateDungeonRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "수정된 던전 정보",
                        "schema": {
                            "$ref": "#/definitions/game_eating_pizza_internal_api_dto.DungeonResponse"
                        }
                    },
                    "400": {
                        "description": "잘못된 요청",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "인증 실패",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "던전을 찾을 수 없음",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "서버 오류",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "던전을 삭제합니다",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dungeons"
                ],
                "summary": "던전 삭제",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "던전 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "잘못된 요청",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "인증 실패",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "던전을 찾을 수 없음",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "서버 오류",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/dungeons/{id}/clear": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "던전을 클리어하고 보상을 획득합니다",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dungeons"
                ],
                "summary": "던전 클리어",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "던전 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "클리어 성공",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "잘못된 요청",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "인증 실패",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/dungeons/{id}/enter": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "던전에 입장합니다",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dungeons"
                ],
                "summary": "던전 입장",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "던전 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "입장 성공",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "잘못된 요청",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "인증 실패",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "서버 오류",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/players": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "플레이어 목록을 페이지네이션으로 조회합니다",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "players"
                ],
                "summary": "플레이어 목록 조회",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "조회 개수 (기본값: 10)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "건너뛸 개수 (기본값: 0)",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "플레이어 목록",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/game_eating_pizza_internal_api_dto.PlayerResponse"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "서버 오류",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/players/leaderboard": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "레벨이 높은 상위 플레이어 목록을 조회합니다",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "players"
                ],
                "summary": "리더보드 조회",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "조회할 플레이어 수 (기본값: 10)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "리더보드",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/game_eating_pizza_internal_api_dto.PlayerResponse"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "서버 오류",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/players/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "현재 로그인한 플레이어의 정보를 조회합니다",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "players"
                ],
                "summary": "내 정보 조회",
                "responses": {
                    "200": {
                        "description": "플레이어 정보",
                        "schema": {
                            "$ref": "#/definitions/game_eating_pizza_internal_api_dto.PlayerResponse"
                        }
                    },
                    "401": {
                        "description": "인증 실패",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "플레이어를 찾을 수 없음",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "현재 로그인한 플레이어의 정보를 수정합니다",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "players"
                ],
                "summary": "내 정보 수정",
                "parameters": [
                    {
                        "description": "수정할 정보",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/game_eating_pizza_internal_api_dto.UpdateMeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "수정된 플레이어 정보",
                        "schema": {
                            "$ref": "#/definitions/game_eating_pizza_internal_api_dto.PlayerResponse"
                        }
                    },
                    "401": {
                        "description": "인증 실패",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "플레이어를 찾을 수 없음",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/players/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "ID로 플레이어 정보를 조회합니다",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "players"
                ],
                "summary": "플레이어 상세 조회",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "플레이어 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "플레이어 정보",
                        "schema": {
                            "$ref": "#/definitions/game_eating_pizza_internal_api_dto.PlayerResponse"
                        }
                    },
                    "401": {
                        "description": "인증 실패",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "플레이어를 찾을 수 없음",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "본인 계정만 삭제할 수 있습니다 (소프트 삭제)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "players"
                ],
                "summary": "플레이어 삭제",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "플레이어 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "잘못된 요청",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "인증 실패",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "403": {
                        "description": "본인만 삭제 가능",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "플레이어를 찾을 수 없음",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/weapons": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "현재 로그인한 플레이어의 무기 목록을 조회합니다",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "weapons"
                ],
                "summary": "무기 목록 조회",
                "responses": {
                    "200": {
                        "description": "무기 목록",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "인증 실패",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "서버 오류",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "새로운 무기를 생성합니다",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "weapons"
                ],
                "summary": "무기 생성",
                "parameters": [
                    {
                        "description": "무기 생성 정보",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/game_eating_pizza_internal_api_dto.CreateWeaponRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "생성된 무기 정보",
                        "schema": {
                            "$ref": "#/definitions/game_eating_pizza_internal_api_dto.WeaponResponse"
                        }
                    },
                    "400": {
                        "description": "잘못된 요청",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "인증 실패",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "서버 오류",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/weapons/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "ID로 무기 정보를 조회합니다 (본인 소유만 가능)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "weapons"
                ],
                "summary": "무기 상세 조회",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "무기 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "무기 정보",
                        "schema": {
                            "$ref": "#/definitions/game_eating_pizza_internal_api_dto.WeaponResponse"
                        }
                    },
                    "401": {
                        "description": "인증 실패",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "403": {
                        "description": "소유한 무기가 아님",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "무기를 찾을 수 없음",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "무기 정보를 수정합니다 (본인 소유만 가능)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "weapons"
                ],
                "summary": "무기 수정",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "무기 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "수정할 무기 정보",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/game_eating_pizza_internal_api_dto.UpdateWeaponRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "수정된 무기 정보",
                        "schema": {
                            "$ref": "#/definitions/game_eating_pizza_internal_api_dto.WeaponResponse"
                        }
                    },
                    "400": {
                        "description": "잘못된 요청",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "인증 실패",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "403": {
                        "description": "소유한 무기가 아님",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "무기를 찾을 수 없음",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "무기를 삭제합니다 (본인 소유만 가능)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "weapons"
                ],
                "summary": "무기 삭제",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "무기 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "인증 실패",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "403": {
                        "description": "소유한 무기가 아님",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "무기를 찾을 수 없음",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/weapons/{id}/equip": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "무기를 장착하여 현재 무기로 설정합니다",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "weapons"
                ],
                "summary": "무기 장착",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "무기 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "장착 성공",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "잘못된 요청",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "인증 실패",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "서버 오류",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/weapons/{id}/upgrade": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "무기를 강화하여 공격력을 증가시킵니다",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "weapons"
                ],
                "summary": "무기 강화",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "무기 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "강화된 무기 정보",
                        "schema": {
                            "$ref": "#/definitions/game_eating_pizza_internal_api_dto.WeaponResponse"
                        }
                    },
                    "400": {
                        "description": "잘못된 요청",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "인증 실패",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "서버 오류",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "game_eating_pizza_internal_api_dto.CreateDungeonRequest": {
            "type": "object",
            "required": [
                "name",
                "type"
            ],
            "properties": {
                "difficulty": {
                    "type": "integer",
                    "example": 1
                },
                "end_time": {
                    "type": "string"
                },
                "is_active": {
                    "description": "omitempty면 기본 true",
                    "type": "boolean"
                },
                "name": {
                    "type": "string",
                    "example": "초급 던전"
                },
                "start_time": {
                    "type": "string"
                },
                "type": {
                    "description": "normal, event, boss",
                    "type": "string",
                    "example": "normal"
                }
            }
        },
        "game_eating_pizza_internal_api_dto.CreateWeaponRequest": {
            "type": "object",
            "required": [
                "name",
                "type"
            ],
            "properties": {
                "attack_power": {
                    "type": "integer",
                    "example": 10
                },
                "attack_speed": {
                    "type": "number",
                    "example": 1
                },
                "name": {
                    "type": "string",
                    "example": "Iron Sword"
                },
                "playerID": {
                    "description": "인증 컨텍스트에서 설정",
                    "type": "integer"
                },
                "rarity": {
                    "description": "common, rare, epic, legendary",
                    "type": "string",
                    "example": "common"
                },
                "type": {
                    "description": "sword, bow, staff",
                    "type": "string",
                    "example": "sword"
                }
            }
        },
        "game_eating_pizza_internal_api_dto.DungeonResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "difficulty": {
                    "type": "integer"
                },
                "end_time": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_active": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "start_time": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "game_eating_pizza_internal_api_dto.LoginRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "example": "secret123"
                },
                "username": {
                    "type": "string",
                    "example": "player1"
                }
            }
        },
        "game_eating_pizza_internal_api_dto.PlayerResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "experience": {
                    "type": "integer"
                },
                "gold": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "level": {
                    "type": "integer"
                },
                "max_distance": {
                    "type": "number"
                },
                "total_kills": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "game_eating_pizza_internal_api_dto.RefreshTokenRequest": {
            "type": "object"
        },
        "game_eating_pizza_internal_api_dto.RegisterRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "minLength": 6,
                    "example": "secret123"
                },
                "username": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 3,
                    "example": "player1"
                }
            }
        },
        "game_eating_pizza_internal_api_dto.UpdateDungeonRequest": {
            "type": "object",
            "properties": {
                "difficulty": {
                    "type": "integer",
                    "example": 2
                },
                "end_time": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean",
                    "example": true
                },
                "name": {
                    "type": "string",
                    "example": "수정된 던전"
                },
                "start_time": {
                    "type": "string"
                },
                "type": {
                    "type": "string",
                    "example": "event"
                }
            }
        },
        "game_eating_pizza_internal_api_dto.UpdateMeRequest": {
            "type": "object",
            "properties": {
                "experience": {
                    "type": "integer",
                    "example": 100
                },
                "gold": {
                    "type": "integer",
                    "example": 500
                },
                "level": {
                    "type": "integer",
                    "example": 2
                },
                "max_distance": {
                    "type": "number",
                    "example": 150.5
                },
                "playerID": {
                    "description": "인증 컨텍스트에서 설정",
                    "type": "integer"
                },
                "total_kills": {
                    "type": "integer",
                    "example": 10
                }
            }
        },
        "game_eating_pizza_internal_api_dto.UpdateWeaponRequest": {
            "type": "object",
            "properties": {
                "attack_power": {
                    "type": "integer",
                    "example": 15
                },
                "attack_speed": {
                    "type": "number",
                    "example": 1.2
                },
                "level": {
                    "type": "integer",
                    "example": 2
                },
                "name": {
                    "type": "string",
                    "example": "Steel Sword"
                },
                "rarity": {
                    "type": "string",
                    "example": "rare"
                },
                "type": {
                    "type": "string",
                    "example": "sword"
                }
            }
        },
        "game_eating_pizza_internal_api_dto.WeaponResponse": {
            "type": "object",
            "properties": {
                "attack_power": {
                    "type": "integer"
                },
                "attack_speed": {
                    "type": "number"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "level": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "player_id": {
                    "type": "integer"
                },
                "rarity": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Tiny Breakers API",
	Description:      "Tiny Breakers: The Beating World - 횡스크롤 방치형 게임 백엔드 API 서버 (걸음 수 연동, 멀티플레이 레이드 지원)",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
